
:- assert_clauses(n(app,3),[
 clause([n(app,3),[n([],0)],$x,$x],
  [&],
  [x]/0),
 clause([n(app,3),[n('[|]',2),$e,$x],$y,[n('[|]',2),$e,$z]],
  [n(app,3),$x,$y,$z],
  [e,x,y,z]/0)
]).

:- assert_clauses(n(rev,2),[
 clause([n(rev,2),[n([],0)],[n([],0)]],
  [&],
  []/0),
 clause([n(rev,2),[n('[|]',2),$e,$x],$y],
  [&,[n(rev,2),$x,$z],[n(app,3),$z,[n('[|]',2),$e,[n([],0)]],$y]],
  [e,x,y,z]/0)
]).
