
:- assert_clauses(n(expr_bl,4),[
 clause([n(expr_bl,4),$xs,$xs,$l,$l],
  [&],
  [xs,l]/0),
 clause([n(expr_bl,4),[n('[|]',2),[n(op,0)],$xs0],$xs,[n(l,1),$l0],$l],
  [&,[n(expr_bl2,4),$xs0,$xs1,$l0,$l1],[n(expr_bl2,4),$xs1,$xs,$l1,$l]],
  [xs0,xs,l0,l,xs1,l1]/0)
]).

:- assert_clauses(n(expr_bl2,4),[
 clause([n(expr_bl2,4),$xs0,$xs,$l0,$l],
  [n(expr_bl,4),$xs0,$xs,$l0,$l],
  [xs0,xs,l0,l]/0)
]).
