
:- assert_clauses(n(add,3),[
 clause([n(add,3),[n(0,0)],$x,$x],
  [&],
  [x]/0),
 clause([n(add,3),[n(s,1),$x],$y,[n(s,1),$z]],
  [n(add,3),$x,$y,$z],
  [x,y,z]/0)
]).

:- assert_clauses(n(fib2,2),[
 clause([n(fib2,2),[n(0,0)],[n(s,1),[n(0,0)]]],
  [&],
  []/0),
 clause([n(fib2,2),[n(s,1),[n(0,0)]],[n(s,1),[n(0,0)]]],
  [&],
  []/0),
 clause([n(fib2,2),[n(s,1),[n(s,1),$n]],$f],
  [&,[n(fib2,2),[n(s,1),$n],$f1],[n(fib2,2),$n,$f2],[n(add,3),$f1,$f2,$f]],
  [n,f,f1,f2]/0)
]).
