[cases(gr(?x5),
  cases(gr(?x6),
   cases(gr(?x7),
    [gr(?x7) & gr(?x6),
     gr(?x7) & gr(?x6) & gr(?x5),
     gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
     gr([?x7]) <=> gr(?x7) by lemma(axiom_2_5_single_element_list),
     gr(?x7) => gr(s(?x7)),
     assume(~ gr([?x7]),
      contra(gr(s(?x7)),
       [gr(s(?x7)),
        gr([?x7]),
        ff]),
      ~ gr(s(?x7))),
     gr(s(?x7)) & gr(?x6),
     gr([?x5]) <=> gr(?x5) by lemma(axiom_2_5_single_element_list),
     gr(?x5) => gr(s(?x5)),
     assume(~ gr([?x5]),
      contra(gr(s(?x5)),
       [gr(s(?x5)),
        gr([?x5]),
        ff]),
      ~ gr(s(?x5))),
     gr(s(?x7)) & gr(?x6) & gr(s(?x5)),
     gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
     ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)),
     assume(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),[],
      gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
      ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))],
    ~ gr(?x7),
    [contra(gr(?x7) & gr(?x6),[gr(?x7),~ gr(?x7),ff]),
     ~ (gr(?x7) & gr(?x6)),
     contra(gr(?x7) & gr(?x6) & gr(?x5),
      [gr(?x7) & gr(?x6),
       ~ (gr(?x7) & gr(?x6)),
       ff]),
     ~ (gr(?x7) & gr(?x6) & gr(?x5)),
     contra(~ gr(?x6),[]),
     ~ ~ gr(?x6),
     contra(~ gr(?x7) & ~ gr(?x6),[]),
     ~ (~ gr(?x7) & ~ gr(?x6)),
     contra(~ gr(?x7) & ~ gr(?x6) & gr(?x5),
      [~ gr(?x7) & ~ gr(?x6),
       ~ (~ gr(?x7) & ~ gr(?x6)),
       ff]),
     ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     contra(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
      cases(
       [case(~ gr(?x7) & ~ gr(?x6) & gr(?x5),
         [~ gr(?x7) & ~ gr(?x6) & gr(?x5),
          ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
          ff]),
        case(gr(?x7) & gr(?x6) & gr(?x5),
         [gr(?x7) & gr(?x6) & gr(?x5),
          ~ (gr(?x7) & gr(?x6) & gr(?x5)),
          ff])],
       ff)),
     ~ (gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     assume(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),[],
      gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
      ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))],
    gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5) => 
     gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
     ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5))),
   ~ gr(?x6),
   cases(gr(?x7),
    [contra(gr(?x7) & gr(?x6),[]),
     ~ (gr(?x7) & gr(?x6)),
     contra(gr(?x7) & gr(?x6) & gr(?x5),
      [gr(?x7) & gr(?x6),
       ~ (gr(?x7) & gr(?x6)),
       ff]),
     ~ (gr(?x7) & gr(?x6) & gr(?x5)),
     contra(~ gr(?x7),[]),
     ~ ~ gr(?x7),
     contra(~ gr(?x7) & ~ gr(?x6),
      [gr(?x7),
       ~ gr(?x7),
       ff]),
     ~ (~ gr(?x7) & ~ gr(?x6)),
     contra(~ gr(?x7) & ~ gr(?x6) & gr(?x5),
      [~ gr(?x7) & ~ gr(?x6),
       ~ (~ gr(?x7) & ~ gr(?x6)),
       ff]),
     ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     contra(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
      cases(
       [case(~ gr(?x7) & ~ gr(?x6) & gr(?x5),
         [~ gr(?x7) & ~ gr(?x6) & gr(?x5),
          ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
          ff]),
        case(gr(?x7) & gr(?x6) & gr(?x5),
         [gr(?x7) & gr(?x6) & gr(?x5),
          ~ (gr(?x7) & gr(?x6) & gr(?x5)),
          ff])],
       ff)),
     ~ (gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     assume(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),[],
      gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
      ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))],
    ~ gr(?x7),
    [~ gr(?x7) & ~ gr(?x6),
     ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
     gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
     ~ gr([?x7]) <=> ~ gr(?x7) by 
      lemma(axiom_2_5_single_element_list_de_morgan),
     gr(?x7) => gr(s(?x7)),
     assume(~ gr([?x7]),
      contra(gr(s(?x7)),
       [gr(s(?x7)),
        gr([?x7]),
        ff]),
      ~ gr(s(?x7))),
     ~ gr(s(?x7)) & ~ gr(?x6),
     gr([?x5]) <=> gr(?x5) by lemma(axiom_2_5_single_element_list),
     gr(?x5) => gr(s(?x5)),
     assume(~ gr([?x5]),
      contra(gr(s(?x5)),
       [gr(s(?x5)),
        gr([?x5]),
        ff]),
      ~ gr(s(?x5))),
     ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)),
     gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
     ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)),
     assume(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),[],
      gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
      ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))],
    gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5) => 
     gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
     ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5))),
   gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5) => 
    gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
    ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5))),
  ~ gr(?x5),
  cases(gr(?x6),
   cases(gr(?x7),
    [contra(gr(?x7) & gr(?x6) & gr(?x5),[]),
     ~ (gr(?x7) & gr(?x6) & gr(?x5)),
     contra(~ gr(?x7) & ~ gr(?x6) & gr(?x5),[]),
     ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     contra(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
      cases(
       [case(~ gr(?x7) & ~ gr(?x6) & gr(?x5),
         [~ gr(?x7) & ~ gr(?x6) & gr(?x5),
          ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
          ff]),
        case(gr(?x7) & gr(?x6) & gr(?x5),
         [gr(?x7) & gr(?x6) & gr(?x5),
          ~ (gr(?x7) & gr(?x6) & gr(?x5)),
          ff])],
       ff)),
     ~ (gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     assume(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),[],
      gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
      ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))],
    ~ gr(?x7),
    [contra(gr(?x7) & gr(?x6) & gr(?x5),[]),
     ~ (gr(?x7) & gr(?x6) & gr(?x5)),
     contra(~ gr(?x7) & ~ gr(?x6) & gr(?x5),[]),
     ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     contra(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
      cases(
       [case(~ gr(?x7) & ~ gr(?x6) & gr(?x5),
         [~ gr(?x7) & ~ gr(?x6) & gr(?x5),
          ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
          ff]),
        case(gr(?x7) & gr(?x6) & gr(?x5),
         [gr(?x7) & gr(?x6) & gr(?x5),
          ~ (gr(?x7) & gr(?x6) & gr(?x5)),
          ff])],
       ff)),
     ~ (gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     assume(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),[],
      gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
      ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))],
    gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5) => 
     gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
     ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5))),
   ~ gr(?x6),
   cases(gr(?x7),
    [contra(gr(?x7) & gr(?x6) & gr(?x5),[]),
     ~ (gr(?x7) & gr(?x6) & gr(?x5)),
     contra(~ gr(?x7) & ~ gr(?x6) & gr(?x5),[]),
     ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     contra(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
      cases(
       [case(~ gr(?x7) & ~ gr(?x6) & gr(?x5),
         [~ gr(?x7) & ~ gr(?x6) & gr(?x5),
          ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
          ff]),
        case(gr(?x7) & gr(?x6) & gr(?x5),
         [gr(?x7) & gr(?x6) & gr(?x5),
          ~ (gr(?x7) & gr(?x6) & gr(?x5)),
          ff])],
       ff)),
     ~ (gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     assume(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),[],
      gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
      ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))],
    ~ gr(?x7),
    [contra(gr(?x7) & gr(?x6) & gr(?x5),[]),
     ~ (gr(?x7) & gr(?x6) & gr(?x5)),
     contra(~ gr(?x7) & ~ gr(?x6) & gr(?x5),[]),
     ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     contra(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),
      cases(
       [case(~ gr(?x7) & ~ gr(?x6) & gr(?x5),
         [~ gr(?x7) & ~ gr(?x6) & gr(?x5),
          ~ (~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
          ff]),
        case(gr(?x7) & gr(?x6) & gr(?x5),
         [gr(?x7) & gr(?x6) & gr(?x5),
          ~ (gr(?x7) & gr(?x6) & gr(?x5)),
          ff])],
       ff)),
     ~ (gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5)),
     assume(gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5),[],
      gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
      ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))],
    gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5) => 
     gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
     ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5))),
   gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5) => 
    gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
    ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5))),
  gr(?x7) & gr(?x6) & gr(?x5) \/ ~ gr(?x7) & ~ gr(?x6) & gr(?x5) => 
   gr(s(?x7)) & gr(?x6) & gr(s(?x5)) \/
   ~ gr(s(?x7)) & ~ gr(?x6) & gr(s(?x5)))].