[lemma(t12,
  all [x1]: (succeeds t(?x1) => gr(?x1) \/ ~ gr(?x1)),
  induction([all [x1]: (succeeds t(?x1) => gr(?x1) \/ ~ gr(?x1))],
   [step([],[],ff by gap,gr([]) \/ ~ gr([])),
    step([x2,x3],
     [gr(?x3) \/ ~ gr(?x3),
      succeeds t(?x3)],
     ff by gap,
     gr([?x2|?x3]) \/ ~ gr([?x2|?x3]))])),
 lemma(s01,
  all []: (fails s),
  ff by gap),
 lemma(r01,
  all []: (succeeds r),
  ff by gap),
 lemma(q01,
  all []: (succeeds q),
  ff by gap),
 lemma(p12,
  all [x1]: (succeeds p(?x1) => gr(?x1)),
  induction([all [x1]: (succeeds p(?x1) => gr(?x1))],
   [step([],[],ff by gap,gr([])),
    step([x2],
     [gr(?x2),
      succeeds p(?x2)],
     ff by gap,
     gr([a|?x2]))]))].