[lemma(u11,
  all [x1]: (succeeds u(?x1) => gr(?x1) \/ ~ gr(?x1)),
  induction([all [x1]: (succeeds u(?x1) => gr(?x1) \/ ~ gr(?x1))],
   [step([x2],[fails true],ff by gap,gr(?x2) \/ ~ gr(?x2))])),
 lemma(t11,
  all [x1]: (succeeds t(?x1) => gr(?x1) \/ ~ gr(?x1)),
  induction([all [x1]: (succeeds t(?x1) => gr(?x1) \/ ~ gr(?x1))],
   [step([x2],[],ff by gap,gr(?x2) \/ ~ gr(?x2)),
    step([x3],
     [succeeds fail],
     ff by gap,
     gr(?x3) \/ ~ gr(?x3))])),
 lemma(r11,
  all [x1]: (succeeds r(?x1) => gr(?x1)),
  induction([all [x1]: (succeeds r(?x1) => gr(?x1))],
   [step([x2],[succeeds (?x2 = 0 ; ?x2 = 1)],ff by gap,gr(?x2))])),
 lemma(p11,
  all [x1]: (succeeds p(?x1) => gr(?x1) \/ ~ gr(?x1)),
  induction([all [x1]: (succeeds p(?x1) => gr(?x1) \/ ~ gr(?x1))],
   [step([x2],[?x2 <> 0],ff by gap,gr(?x2) \/ ~ gr(?x2))]))].