[lemma(t11,
  all [x1]: (succeeds t(?x1) => gr(?x1) \/ ~ gr(?x1)),
  induction([all [x1]: (succeeds t(?x1) => gr(?x1) \/ ~ gr(?x1))],
   [step([],[],[gr([]) \/ ~ gr([])],gr([]) \/ ~ gr([])),
    step([x2,x3],
     [gr(?x3) \/ ~ gr(?x3),
      succeeds t(?x3)],
     [cases(gr(?x2),
       cases(gr(?x3),
        [gr(?x3) \/ ~ gr(?x3),
         gr(?x2) & gr(?x3),
         gr([?x2|?x3]) => gr(?x2) & gr(?x3),
         assume(~ (gr(?x2) & gr(?x3)),
          contra(gr([?x2|?x3]),
           [gr(?x2) & gr(?x3),
            ff]),
          ~ gr([?x2|?x3])),
         gr([?x2|?x3]) <=> gr(?x2) & gr(?x3) by lemma(axiom_2_5),
         gr([?x2|?x3]) \/ ~ gr([?x2|?x3]),
         assume(gr(?x3) \/ ~ gr(?x3),[],
          gr([?x2|?x3]) \/ ~ gr([?x2|?x3]))],
        ~ gr(?x3),
        [gr(?x3) \/ ~ gr(?x3),
         ~ gr(?x2) \/ ~ gr(?x3),
         ~ gr([?x2|?x3]) <=> ~ gr(?x2) \/ ~ gr(?x3) by 
          lemma(axiom_2_5_de_morgan),
         gr([?x2|?x3]) \/ ~ gr([?x2|?x3]),
         assume(gr(?x3) \/ ~ gr(?x3),[],
          gr([?x2|?x3]) \/ ~ gr([?x2|?x3]))],
        gr(?x3) \/ ~ gr(?x3) => gr([?x2|?x3]) \/ ~ gr([?x2|?x3])),
       ~ gr(?x2),
       cases(gr(?x3),
        [gr(?x3) \/ ~ gr(?x3),
         ~ gr(?x2) \/ ~ gr(?x3),
         ~ gr([?x2|?x3]) <=> ~ gr(?x2) \/ ~ gr(?x3) by 
          lemma(axiom_2_5_de_morgan),
         gr([?x2|?x3]) \/ ~ gr([?x2|?x3]),
         assume(gr(?x3) \/ ~ gr(?x3),[],
          gr([?x2|?x3]) \/ ~ gr([?x2|?x3]))],
        ~ gr(?x3),
        [gr(?x3) \/ ~ gr(?x3),
         ~ gr(?x2) \/ ~ gr(?x3),
         ~ gr([?x2|?x3]) <=> ~ gr(?x2) \/ ~ gr(?x3) by 
          lemma(axiom_2_5_de_morgan),
         gr([?x2|?x3]) \/ ~ gr([?x2|?x3]),
         assume(gr(?x3) \/ ~ gr(?x3),[],
          gr([?x2|?x3]) \/ ~ gr([?x2|?x3]))],
        gr(?x3) \/ ~ gr(?x3) => gr([?x2|?x3]) \/ ~ gr([?x2|?x3])),
       gr(?x3) \/ ~ gr(?x3) => gr([?x2|?x3]) \/ ~ gr([?x2|?x3]))],
     gr([?x2|?x3]) \/ ~ gr([?x2|?x3]))])),
 lemma(s01,
  all []: (fails s),
  ff by gap),
 lemma(r01,
  all []: (succeeds r),
  ff by gap),
 lemma(q01,
  all []: (succeeds q),
  ff by gap),
 lemma(p11,
  all [x1]: (succeeds p(?x1) => gr(?x1)),
  induction([all [x1]: (succeeds p(?x1) => gr(?x1))],
   [step([],[],[],gr([])),
    step([x2],
     [gr(?x2),
      succeeds p(?x2)],
     [cases(gr(?x2),
       [gr(a) & gr(?x2),
        gr([a|?x2]) => gr(a) & gr(?x2),
        assume(~ (gr(a) & gr(?x2)),
         contra(gr([a|?x2]),
          [gr(a) & gr(?x2),
           ff]),
         ~ gr([a|?x2])),
        gr([a|?x2]) <=> gr(a) & gr(?x2) by lemma(axiom_2_5),
        assume(gr(?x2),[],
         gr([a|?x2]))],
       ~ gr(?x2),
       [assume(gr(?x2),[],gr([a|?x2]))],
       gr(?x2) => gr([a|?x2]))],
     gr([a|?x2]))]))].